/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author seruj
 */
public class Booking extends javax.swing.JFrame {

    /**
     * Creates new form Booking
     */
    public Booking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bnic = new javax.swing.JTextField();
        bsize = new javax.swing.JComboBox<>();
        q1 = new javax.swing.JRadioButton();
        q2 = new javax.swing.JRadioButton();
        q3 = new javax.swing.JRadioButton();
        bbrand = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        blocation = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(229, 229, 229));

        jButton3.setBackground(new java.awt.Color(229, 229, 229,50));
        jButton3.setForeground(new java.awt.Color(229, 229, 229));
        jButton3.setIcon(new javax.swing.ImageIcon("F:\\Assignments\\sem 3\\samanthi mam\\gas reservation system\\Interface\\222222.png")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 0,0));

        jLabel2.setBackground(new java.awt.Color(20, 33, 61));
        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(20, 33, 61));
        jLabel2.setText("N.I.C : ");

        jLabel3.setBackground(new java.awt.Color(20, 33, 61));
        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(20, 33, 61));
        jLabel3.setText("Quantity : ");

        jLabel4.setBackground(new java.awt.Color(20, 33, 61));
        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(20, 33, 61));
        jLabel4.setText("Gas Size : ");

        jLabel5.setBackground(new java.awt.Color(20, 33, 61));
        jLabel5.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(20, 33, 61));
        jLabel5.setText("Location : ");

        jLabel6.setBackground(new java.awt.Color(20, 33, 61));
        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(20, 33, 61));
        jLabel6.setText("Gas Brand : ");

        bnic.setBackground(new java.awt.Color(229, 229, 229));
        bnic.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        bnic.setForeground(new java.awt.Color(20, 33, 61));
        bnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnicActionPerformed(evt);
            }
        });

        bsize.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        bsize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Medium" }));
        bsize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsizeActionPerformed(evt);
            }
        });

        q1.setBackground(new java.awt.Color(229, 229, 229));
        buttonGroup1.add(q1);
        q1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        q1.setForeground(new java.awt.Color(20, 33, 61));
        q1.setText("1");

        q2.setBackground(new java.awt.Color(229, 229, 229));
        buttonGroup1.add(q2);
        q2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        q2.setForeground(new java.awt.Color(20, 33, 61));
        q2.setText("2");
        q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2ActionPerformed(evt);
            }
        });

        q3.setBackground(new java.awt.Color(229, 229, 229));
        buttonGroup1.add(q3);
        q3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        q3.setForeground(new java.awt.Color(20, 33, 61));
        q3.setText("3");

        bbrand.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        bbrand.setForeground(new java.awt.Color(20, 33, 61));
        bbrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.LITRO", "2.LAUGFS" }));

        jButton1.setBackground(new java.awt.Color(20, 33, 61));
        jButton1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(229, 229, 229));
        jButton1.setText("Reserve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        blocation.setBackground(new java.awt.Color(229, 229, 229));
        blocation.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        blocation.setForeground(new java.awt.Color(20, 33, 61));
        blocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. Colombo", " ", "2. Gampaha", " ", "3. Kalutara", " ", "4. Kandy", " ", "5. Matale", " ", "6. Nuwara Eliya", " ", "7. Galle", " ", "8. Matara", " ", "9. Hambantota", " ", "10. Jaffna", " ", "11. Kilinochchi", " ", "12. Mannar", " ", "13. Vavuniya", " ", "14. Mullaitivu", " ", "15. Batticaloa", " ", "16. Ampara", " ", "17. Trincomalee", " ", "18. Kurunegala", " ", "19. Puttalam", " ", "20. Anuradhapura", " ", "21. Polonnaruwa", " ", "22. Badulla", " ", "23. Moneragala", " ", "24. Ratnapura", " ", "25. Kegalle" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(250, 250, 250))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bbrand, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bnic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(blocation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(212, 212, 212)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(q1)
                                        .addGap(18, 18, 18)
                                        .addComponent(q2)
                                        .addGap(18, 18, 18)
                                        .addComponent(q3))
                                    .addComponent(jLabel3))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bsize, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 144, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnic, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q1)
                    .addComponent(q2)
                    .addComponent(q3))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsize, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blocation, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bbrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 880, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\Assignments\\sem 3\\samanthi mam\\gas reservation system\\Interface\\booking.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnicActionPerformed

    private void bsizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bsizeActionPerformed

    private void q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Connection c = null;
            PreparedStatement s = null;
            Statement s1 = null;
            ResultSet r = null;
            
            Class.forName("com.mysql.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/gasreservation","root","");
            String sql = "insert into booking values (?,?,?,?,?)";
            s = c.prepareStatement(sql);
            
            String q = null;
            if (q1.isSelected()){
               q = q1.getText();
            }else if (q2.isSelected()){
               q = q2.getText();
            }else if (q3.isSelected()){
               q = q3.getText();
            }else {
               JOptionPane.showMessageDialog(rootPane, "Please select the Quantity!");
            }
            s.setString(2, q);
            
            s.setString(3, bsize.getSelectedItem().toString());
            s.setString(4, bbrand.getSelectedItem().toString());
            s.setString(5, blocation.getSelectedItem().toString());
            
            String b1= bnic.getText();
            String sql2 = "Select * from account where NIC='"+b1+"'";
            r = s.executeQuery(sql2);
            if (r.next()){
                s.setString(1,b1);
                s.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Booking Details have been added!");
            }else {
                JOptionPane.showMessageDialog(rootPane, "Wrong NIC Number!");
            }
            
            
            
        }catch (Exception e){
            System.out.println(e);       
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        Home h = new Home();

        h.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bbrand;
    private javax.swing.JComboBox<String> blocation;
    private javax.swing.JTextField bnic;
    private javax.swing.JComboBox<String> bsize;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton q1;
    private javax.swing.JRadioButton q2;
    private javax.swing.JRadioButton q3;
    // End of variables declaration//GEN-END:variables
}
